# Generated by Django 5.2.17 on 2026-10-01 16:37

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('OPERATOR', 'Operador PNAE'), ('MANAGER', 'Gestor')], default='OPERATOR', max_length=20, verbose_name='perfil')),
                ('can_authorize_extras', models.BooleanField(default=False, verbose_name='pode autorizar excedente')),
                ('can_reverse_deliveries', models.BooleanField(default=False, verbose_name='pode estornar entrega')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='acesso ao admin')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='criado em')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='campus.campus', verbose_name='campus')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'ordering': ['name'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
