# Generated by Django 5.2.17 on 2026-10-01 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='arquivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('VALIDATING', 'Validando'), ('PREVIEW', 'Prévia'), ('APPLIED', 'Aplicada'), ('FAILED', 'Falhou')], default='PENDING', max_length=20, verbose_name='situação')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='linhas totais')),
                ('imported_rows', models.PositiveIntegerField(default=0, verbose_name='linhas importadas')),
                ('rejected_rows', models.PositiveIntegerField(default=0, verbose_name='linhas rejeitadas')),
                ('error_report_path', models.CharField(blank=True, max_length=500, verbose_name='relatório de erros')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_jobs', to='campus.campus', verbose_name='campus')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_jobs', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
            ],
            options={
                'verbose_name': 'importação',
                'verbose_name_plural': 'importações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=40, verbose_name='matrícula')),
                ('full_name', models.CharField(max_length=200, verbose_name='nome completo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('qr_token_hash', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='hash do token QR')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='campus.campus', verbose_name='campus')),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='campus.classgroup', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'estudante',
                'verbose_name_plural': 'estudantes',
                'ordering': ['full_name'],
                'constraints': [models.UniqueConstraint(fields=('campus', 'registration_number'), name='uniq_student_campus_registration')],
            },
        ),
    ]
