# Generated by Django 5.2.17 on 2026-10-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='source_file',
            field=models.FileField(blank=True, upload_to='imports/%Y/%m/', verbose_name='arquivo enviado'),
        ),
    ]
