# Generated by Django 5.2.17 on 2026-10-02 03:35

import apps.students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_importjob_source_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='academic_year',
            field=models.PositiveIntegerField(default=apps.students.models._current_year, verbose_name='ano letivo'),
        ),
    ]
