# Generated by Django 5.2.17 on 2026-10-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_importjob_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, max_length=120, verbose_name='curso'),
        ),
        migrations.AddField(
            model_name='student',
            name='course_code',
            field=models.CharField(blank=True, max_length=40, verbose_name='código do curso'),
        ),
        migrations.AddField(
            model_name='student',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='student',
            name='plan_row',
            field=models.CharField(blank=True, max_length=20, verbose_name='linha da planilha'),
        ),
        migrations.AddField(
            model_name='student',
            name='school_origin',
            field=models.CharField(blank=True, max_length=60, verbose_name='tipo de escola de origem'),
        ),
        migrations.AddField(
            model_name='student',
            name='sexo',
            field=models.CharField(blank=True, max_length=20, verbose_name='sexo'),
        ),
        migrations.AddField(
            model_name='student',
            name='situation_period',
            field=models.CharField(blank=True, max_length=60, verbose_name='situação no período'),
        ),
    ]
