# Generated by Django 5.2.17 on 2026-10-03 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_course_student_course_code_student_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='qr_token_hash',
        ),
    ]
