# Generated by Django 5.2.17 on 2026-10-03 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_student_qr_token_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('password', models.CharField(max_length=128, verbose_name='senha')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='último acesso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='students.student', verbose_name='estudante')),
            ],
            options={
                'verbose_name': 'conta do aluno',
                'verbose_name_plural': 'contas de aluno',
                'ordering': ['email'],
            },
        ),
    ]
