# Generated by Django 5.2.17 on 2026-10-01 16:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        ('menus', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(verbose_name='data do serviço')),
                ('meal_type', models.CharField(choices=[('LUNCH', 'Almoço'), ('DINNER', 'Jantar'), ('SNACK', 'Lanche'), ('OTHER', 'Outro')], max_length=20, verbose_name='refeição')),
                ('planned_start_at', models.DateTimeField(verbose_name='início previsto')),
                ('planned_end_at', models.DateTimeField(verbose_name='fim previsto')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('OPEN', 'Aberta'), ('CLOSED', 'Encerrada'), ('CANCELED', 'Cancelada')], default='DRAFT', max_length=20, verbose_name='situação')),
                ('estimated_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='quantidade prevista')),
                ('extras_enabled_at', models.DateTimeField(blank=True, null=True, verbose_name='excedentes liberados em')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='aberta em')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='encerrada em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='campus.campus', verbose_name='campus')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_distributions', to=settings.AUTH_USER_MODEL, verbose_name='encerrou')),
                ('extras_enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extras_enabled_distributions', to=settings.AUTH_USER_MODEL, verbose_name='liberou excedentes')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='menus.menu', verbose_name='cardápio')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_distributions', to=settings.AUTH_USER_MODEL, verbose_name='abriu')),
            ],
            options={
                'verbose_name': 'distribuição',
                'verbose_name_plural': 'distribuições',
                'ordering': ['-service_date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('REGULAR', 'Regular'), ('EXCEDENTE', 'Excedente')], max_length=20, verbose_name='tipo')),
                ('delivered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='entregue em')),
                ('reason', models.TextField(blank=True, verbose_name='motivo')),
                ('status', models.CharField(choices=[('VALIDA', 'Válida'), ('ESTORNADA', 'Estornada')], default='VALIDA', max_length=20, verbose_name='situação')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='estornada em')),
                ('reversal_reason', models.TextField(blank=True, verbose_name='motivo do estorno')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authorized_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='autorizada por')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='registrada por')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='estornada por')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='students.student', verbose_name='estudante')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='distributions.distribution', verbose_name='distribuição')),
            ],
            options={
                'verbose_name': 'entrega',
                'verbose_name_plural': 'entregas',
                'ordering': ['-delivered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['campus', 'service_date', 'status'], name='idx_dist_campus_date_status'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['distribution', 'student'], name='idx_delivery_dist_student'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_type__in', ['REGULAR', 'EXCEDENTE'])), name='chk_delivery_type'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['VALIDA', 'ESTORNADA'])), name='chk_delivery_status'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_type', 'REGULAR'), models.Q(models.Q(('reason', ''), _negated=True), ('authorized_by__isnull', False)), _connector='OR'), name='chk_delivery_extras_requires_reason_authorizer'),
        ),
    ]
