# Generated by Django 5.2.17 on 2026-10-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0002_partial_unique_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='meal_type',
            field=models.CharField(choices=[('LUNCH', 'Almoço'), ('DINNER', 'Jantar'), ('SNACK', 'Lanche'), ('OTHER', 'Outro')], default='SNACK', max_length=20, verbose_name='refeição'),
        ),
    ]
