# Generated by Django 5.2.17 on 2026-10-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0003_alter_distribution_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='auto_open',
            field=models.BooleanField(default=False, verbose_name='gerada em lote'),
        ),
    ]
