# Generated by Django 5.2.17 on 2026-10-01 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='código')),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=64, verbose_name='fuso horário')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'campus',
                'verbose_name_plural': 'campus',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='turma')),
                ('course', models.CharField(blank=True, max_length=120, verbose_name='curso')),
                ('academic_year', models.PositiveIntegerField(verbose_name='ano letivo')),
                ('active', models.BooleanField(default=True, verbose_name='ativa')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_groups', to='campus.campus', verbose_name='campus')),
            ],
            options={
                'verbose_name': 'turma',
                'verbose_name_plural': 'turmas',
                'ordering': ['campus', 'academic_year', 'name'],
                'constraints': [models.UniqueConstraint(fields=('campus', 'name', 'academic_year'), name='uniq_classgroup_campus_name_year')],
            },
        ),
    ]
