# Generated by Django 5.2.17 on 2026-10-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='display_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='turma (exibição)'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='source_code',
            field=models.CharField(blank=True, max_length=60, verbose_name='código de origem'),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='name',
            field=models.CharField(max_length=120, verbose_name='turma (código)'),
        ),
    ]
