# Generated by Django 5.2.17 on 2026-10-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_classgroup_display_name_classgroup_source_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='campus/', verbose_name='logo'),
        ),
    ]
