# Generated by Django 5.2.17 on 2026-10-01 16:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80, verbose_name='ação')),
                ('entity_type', models.CharField(max_length=80, verbose_name='entidade')),
                ('entity_id', models.CharField(max_length=64, verbose_name='id da entidade')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ocorrido em')),
                ('metadata_json', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='campus.campus', verbose_name='campus')),
            ],
            options={
                'verbose_name': 'evento de auditoria',
                'verbose_name_plural': 'eventos de auditoria',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['campus', 'occurred_at'], name='idx_audit_campus_time'), models.Index(fields=['entity_type', 'entity_id'], name='idx_audit_entity')],
            },
        ),
    ]
