# Generated by Django 5.2.17 on 2026-10-01 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(verbose_name='data do serviço')),
                ('meal_type', models.CharField(choices=[('LUNCH', 'Almoço'), ('DINNER', 'Jantar'), ('SNACK', 'Lanche'), ('OTHER', 'Outro')], max_length=20, verbose_name='refeição')),
                ('description', models.TextField(verbose_name='descrição')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menus', to='campus.campus', verbose_name='campus')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menus', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
            ],
            options={
                'verbose_name': 'cardápio',
                'verbose_name_plural': 'cardápios',
                'ordering': ['-service_date', 'meal_type'],
                'indexes': [models.Index(fields=['campus', 'service_date', 'meal_type'], name='idx_menu_campus_date_type')],
            },
        ),
    ]
