# Generated by Django 5.2.17 on 2026-10-03 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_menu_uniq_menu_campus_date_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='published',
            field=models.BooleanField(default=False, verbose_name='publicado para o aluno'),
        ),
        migrations.AddField(
            model_name='menu',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='publicado em'),
        ),
        migrations.AddField(
            model_name='menu',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_menus', to=settings.AUTH_USER_MODEL, verbose_name='publicado por'),
        ),
    ]
